In [196]:
import pandas as pd
import numpy as np
import csv

In [ ]:
x=1

In [246]:
expert_dlc_file_path = r"C:\Users\Mohamad\Desktop\ssss\1_2022-06-29@15_07_03f570672_RPi_recording_split_one_min_cut_00-41-00\CollectedData_.h5"
inExpert_dlc_file_path = r"X:\Social-Interaction\DLC-Projects\maDLC_SI--2022-07-13\labeled-data\1_2022-06-29@15_07_03f570672_RPi_recording_split_one_min_cut_00-41-00\CollectedData_.h5"

expert_dlc_hdf = pd.read_hdf(expert_dlc_file_path)
inExpert_dlc_hdf = pd.read_hdf(inExpert_dlc_file_path)


In [247]:
expert_dlc_hdf 


scorer                                                                                    \
individuals                                                                       mouse1   
bodyparts                                                                          snout   
coords                                                                                 x   
labeled-data 1_2022-06-29@15_07_03f570672_RPi_recording_spli... img0097.png   191.815356   
                                                                img0107.png   156.072000   
                                                                img0109.png   146.981000   
                                                                img0204.png    98.676284   
                                                                img0205.png   101.108257   
                                                                img0245.png   626.906000   
                                                                img0572.png   782.201791   
                                                                img0858.png   520.788271   
                                                                img0864.png   515.401640   
                                                                img0877.png   498.996000   
                                                                img0883.png   480.848000   
                                                                img0890.png   427.192000   
                                                                img1031.png   843.740000   
                                                                img1032.png   857.304000   
                                                                img1078.png  1112.327671   
                                                                img1246.png   392.097611   
                                                                img1363.png  1103.955674   
                                                                img1368.png  1119.685697   
                                                                img1426.png   857.857879   
                                                                img1431.png   743.782949   

scorer                                                                                   \
individuals                                                                               
bodyparts                                                                                 
coords                                                                                y   
labeled-data 1_2022-06-29@15_07_03f570672_RPi_recording_spli... img0097.png  400.603315   
                                                                img0107.png  262.855000   
                                                                img0109.png  251.380000   
                                                                img0204.png  714.088378   
                                                                img0205.png  715.432240   
                                                                img0245.png  529.328000   
                                                                img0572.png  580.838100   
                                                                img0858.png  262.449000   
                                                                img0864.png  264.053700   
                                                                img0877.png  279.337000   
                                                                img0883.png  357.057000   
                                                                img0890.png  339.862000   
                                                                img1031.png  663.109000   
                                                                img1032.png  660.892000   
                                                                img1078.png  661.373671   
                                                              

In [248]:
#inExpert_dlc_hdf['', 'mouse3', 'leftEar', 'y'].values

In [249]:
inExpert_dlc_hdf

scorer                                                                                    \
individuals                                                                       mouse1   
bodyparts                                                                          snout   
coords                                                                                 x   
labeled-data 1_2022-06-29@15_07_03f570672_RPi_recording_spli... img0097.png   191.897426   
                                                                img0107.png   159.012308   
                                                                img0109.png   149.820912   
                                                                img0204.png    92.332988   
                                                                img0205.png    90.234036   
                                                                img0245.png   624.187445   
                                                                img0572.png   784.014162   
                                                                img0858.png   523.506826   
                                                                img0864.png   520.838751   
                                                                img0877.png   498.996000   
                                                                img0883.png   482.660370   
                                                                img0890.png   432.629111   
                                                                img1031.png   850.083296   
                                                                img1032.png   857.304000   
                                                                img1078.png  1107.796745   
                                                                img1246.png   389.379056   
                                                                img1363.png  1109.392784   
                                                                img1368.png  1128.747548   
                                                                img1426.png   859.670249   
                                                                img1431.png   736.533468   

scorer                                                                                   \
individuals                                                                               
bodyparts                                                                                 
coords                                                                                y   
labeled-data 1_2022-06-29@15_07_03f570672_RPi_recording_spli... img0097.png  398.099307   
                                                                img0107.png  262.855000   
                                                                img0109.png  249.056435   
                                                                img0204.png  713.182193   
                                                                img0205.png  707.276575   
                                                                img0245.png  529.328000   
                                                                img0572.png  582.650470   
                                                                img0858.png  265.167555   
                                                                img0864.png  262.241330   
                                                                img0877.png  286.586481   
                                                                img0883.png  364.306481   
                                                                img0890.png  345.299111   
                                                                img1031.png  664.015185   
                                                                img1032.png  660.892000   
                                                                img1078.png  661.373671   
                                                              

In [250]:
mice = expert_dlc_hdf.columns.levels[1]
bodyparts = expert_dlc_hdf.columns.levels[2]

coord_dict = {}

for bp in bodyparts:
    dist = 0
    for mouse in mice:

        x_Expert = expert_dlc_hdf['', mouse, bp, 'x'].values
        y_Expert = expert_dlc_hdf['', mouse, bp, 'y'].values

        x_inExpert = inExpert_dlc_hdf['', mouse, bp, 'x'].values
        y_inExpert = inExpert_dlc_hdf['', mouse, bp, 'y'].values
        
        # sum_x += np.sum(abs(x_Expert - x_inExpert))    
        # dist += np.sqrt((x_Expert - x_inExpert)**2 + (y_Expert - y_inExpert)**2)
        dist += np.nansum(np.sqrt((x_Expert - x_inExpert)**2 + (y_Expert - y_inExpert)**2))

    # error = sum_x / (len(expert_dlc_hdf) * len(mice))
    error = dist / (len(expert_dlc_hdf) * len(mice))

    coord_dict.update({bp:error})
    
    

In [251]:
coord_dict

{'leftEar': 4.281395285710312,
 'rightEar': 3.267303321794315,
 'shoulder': 5.519250025167691,
 'snout': 4.196802868259956,
 'spine1': 6.050758113930675,
 'spine2': 7.074914600397739,
 'spine3': 7.0344407409819585,
 'spine4': 6.0012706514447185,
 'tail1': 7.007669405975398,
 'tail2': 5.700327666296697,
 'tailBase': 2.812079208866331,
 'tailEnd': 3.359171995734017}

In [252]:

with open('MAE_bp_2users.csv', 'w') as f:  # You will need 'wb' mode in Python 2.x
    w = csv.DictWriter(f, coord_dict.keys())
    w.writeheader()
    w.writerow(coord_dict)

In [145]:
x1 = (expert_dlc_hdf['3Mice_24videos', 'mouse3', 'leftEar', 'x'].values)
y1 = (expert_dlc_hdf['3Mice_24videos', 'mouse3', 'leftEar', 'y'].values)

x2 = (inExpert_dlc_hdf['DLC_dlcrnetms5_DLC_SI_PiCamDec21shuffle1_102500', 'mouse3', 'leftEar', 'x'].values)
y2 = (inExpert_dlc_hdf['DLC_dlcrnetms5_DLC_SI_PiCamDec21shuffle1_102500', 'mouse3', 'leftEar', 'y'].values)


In [139]:
np.sqrt((x1-x2)**2 + (y1-y2)**2)

array([485.14599343])

In [142]:
np.sqrt((x1-x2)**2 + (y1-y2)**2)

array([804.88469522])

In [147]:
np.sqrt((x1-x2)**2 + (y1-y2)**2)

array([370.69944906])

In [148]:
(485.14599343 + 804.88469522 + 370.69944906)/3

553.57671257

In [190]:
import numpy as np

In [195]:
l = [2,4,6,8]
0 + (np.diff(l)/2).astype(int)

array([1, 1, 1])